### ISSUE TITLE
Mouse cursor / Desktop option?

### ISSUE THREAD

**Issue by strarsis** [scriptex/touchsweep#114]
It would be nice if this library also allows to do these gestures using a mouse - and still register them as swipe events.

The touch interaction can be emulated in the Developer Tools - but this requested feature is meant to be used by the user.

**Comment by scriptex** [comment]
Thanks for raising this! 

The primary idea behind this small library is to handle events on touch enabled devices only. 

I am not sure if we need to extend the already existing functionality and what will we achieve by doing so. 

If you think that this will really help, please elaborate or even submit a PR :)

**Comment by scriptex** [comment]
@strarsis this is now available in version 1.3.0 

You can download it from [Github](https://github.com/scriptex/touchsweep/releases/tag/1.3.0) or from [NPM](https://www.npmjs.com/package/touchsweep)
