### ISSUE TITLE
Bug report.

### ISSUE THREAD

**Issue by josuedavid1997** [scriptex/touchsweep#166]
Hello, thanks for this cool library.
But I found a issue.
the startX, startY position is returning wrong number.
Do you have any idea on this problem?
I look forward to hearing from you,

**Comment by scriptex** [comment]
@josuedavid1997 can you please be more specific and explain in a bit more detail what’s wrong? Maybe provide steps to reproduce?

**Comment by josuedavid1997** [comment]
When I do swipe action, I need the start and end position (ClientX, clientY)
BUt I found this: ev.detail.coords.startX

You have startX and startY only

**Comment by scriptex** [comment]
The `coords` object should contain `startX`, `endX`, `moveX`, `startY`, `endY` and `moveY` properties. Are you sure that you are unable to see those? 
Also, what browser are you using?

**Comment by josuedavid1997** [comment]
I can see that startXY, endXY, moveXY. and that's doesn't express the clientX in mobile screen . 
chrome browser

**Comment by scriptex** [comment]
Well, you can calculate this by adding whatever X you need to the `top` of your swipeable area’s `getBoundingClientRect()`

**Comment by scriptex** [comment]
Were you able to solve the problem, @josuedavid1997? If yes, please consider closing the issue 😉
